## NumPy
---

[NumPy](https://numpy.org/)库是Python科学计算环境中最常用的库。它提供了用于处理数组的高效数据结构。Numpy库的核心是使用C语言实现的。

In [1]:
# 为了使用NumPy库，需要先导入它。按照惯例，我们以别名np导入numpy模块。
import numpy as np

Numpy库的核心是表示同质数据的多维数组。数组内所有元素的数据类型是相同的。NumPy中多维数组的主要数据结构是ndarray类（class）。除了保存数组中的数据，这种数据结构还可以包含关于数据的重要描述性的元数据（metaData）。

In [2]:
data = np.array(([1,2],[3,4],[5,6]))
# 变量类型
type(data)

numpy.ndarray

In [3]:
# 数组维度
data.ndim

2

In [4]:
# 数组形状
data.shape

(3, 2)

In [5]:
# 数组元素数目
data.size

6

In [6]:
# 数组元素数目
data.dtype

dtype('int64')

### 数据类型
---

| dtype | 变体 | 说明 |
|---|---|---|
| int | int8, int16, int32, int64 | 整数 |
| unit | unit8, unit16, unit32, unit64 | 无符号整数 |
| bool| bool | 布尔类型 |
| float | float16, float32, float64, float128 | 浮点类型 |
| complex | complex64, complex128, complex256 | 复数浮点类型 |

In [7]:
# 默认数据类型
data = np.array([1,2,3])
print(data.dtype)
# 指定数据类型
data = np.array([1,2,3], dtype=float)
print(data.dtype)

int64
float64


转换数据类型

In [8]:
# 使用 np.array 函数
data = np.array([1,2,3])
print(data.dtype)
data = np.array(data, dtype=float)
print(data.dtype)
# 使用ndarray类内置的astype方法
data = data.astype(np.int64)
print(data.dtype)

int64
float64
int64


根据应用场景，应用合理的数组数据类型。

In [9]:
data = np.array([-1,0,1])
np.sqrt(data)

/tmp/ipykernel_2006731/3897526667.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(data)


array([nan,  0.,  1.])

In [10]:
np.sqrt(data, dtype=complex)

array([0.+1.j, 0.+0.j, 1.+0.j])

In [11]:
# 复数的实部和虚部
np.sqrt(data, dtype=complex).real
np.sqrt(data, dtype=complex).imag

array([1., 0., 0.])

### 内存中数组数据的顺序
---

对于包含行列的二维数据：一种可能的方式是按顺序逐行存储数据；一种可能的方式是按列存储数据。前者为行主序（row-major），后者为列主序（column-major）。C语言使用行主序，Fortran使用主要序列。
NumPy数组默认使用行主序，创建数组时可以使用关键词参数`order='C'`或者`order='F'`设置。当使用借助C或者Fortran编写的接口时，需要特别注意NumPy数组的排序方式。

## 创建数组
---
| 函数名 | 数组类型 |
|---|---|
| np.zeros | 指定维度和类型，以0填充 |
| np.ones | 指定维度和类型，以1填充 |
| np.arange | 创建均匀间隔数组，指定开始值、结束值和增量值 |
| np.linpace | 创建均匀间隔数组，指定开始值、结束值和元素数量 |
| np.random.rand | 创建一个数组，元素为0-1之间均匀分布的随机数 |
| np.zeros_like | 复制一个数组的维度和类型，以0填充 |

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# np.arange 不包括结束值
np.arange(0,5,1)

array([0, 1, 2, 3, 4])

In [14]:
# np.linspace 包括结束值
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

### Meshgrid数组
可以使用函数np.meshgrid生成多维坐标网络。

In [15]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)

In [16]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [17]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

二维坐标数组的常见应用场景是计算包含两个变量x和y的函数，可以用于绘制包含这两个变量的函数图形，如等高线图。

In [18]:
Z = (X + Y) ** 2
print(Z)

[[9 4 1]
 [1 0 1]
 [1 4 9]]


## 数组索引和切片
---

正整数用于从数组开头进行索引（**索引开始于0**），负整数用于从数组结尾进行索引（索引开始于-1）。